# config.yml
language: zh

pipeline:
- name: JiebaTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20251122-220540-feldspar-gofer
